# Generated by Django 5.2.3 on 2025-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(default=False, verbose_name='Автор подій'),
        ),
    ]
