# Generated by Django 5.2.3 on 2025-06-17 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('start_time', models.DateTimeField(verbose_name='Дата початку')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_events', to='events.category', verbose_name='Категорія')),
            ],
        ),
    ]
