# Generated by Django 5.2.3 on 2025-06-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Подія', 'verbose_name_plural': 'Події'},
        ),
    ]
